Inventory/Controllers/GoodsIssueController.cs
using System;
using Inventory.Resources;
using Inventory.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Inventory.Controllers
{
    public class GoodsIssueController : Controller
    {
        private readonly GoodsIssueService giService;
        private readonly WarehouseService warehouseService;
        private readonly ItemService itemService;

        public GoodsIssueController(GoodsIssueService giService, 
                                      WarehouseService warehouseService,
                                      ItemService itemService)
        {
            this.giService = giService;
            this.warehouseService = warehouseService;
            this.itemService = itemService;
        }

        [Authorize]
        public IActionResult Index(Guid? warehouseId, DateTime? startDate, DateTime? endDate)
        {
            if (startDate == null) startDate = DateTime.Today;
            if (endDate == null) endDate = DateTime.Today;

            ViewBag.WarehouseId = warehouseId;
            ViewBag.StartDate = startDate.Value.ToString("yyyy-MM-dd");
            ViewBag.EndDate = endDate.Value.ToString("yyyy-MM-dd");
            ViewBag.WarehouseList = warehouseService.GetList();

            var list = giService.GetList(warehouseId, startDate, endDate);

            return View(list);
        }

        [Authorize]
        public IActionResult Create()
        {
            ViewBag.WarehouseList = warehouseService.GetList();
            ViewBag.ItemList = itemService.GetList();

            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(GoodsIssueResource grRes)
        {
            try
            {
                giService.Create(grRes);
                return Ok();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.GetBaseException().Message);
            }
        }

        [Authorize]
        public IActionResult Get(Guid? id)
        {
            var grRes = giService.Get(id);
            return Ok(grRes);
        }

        [Authorize]
        public IActionResult Update(Guid id)
        {
            ViewBag.WarehouseList = warehouseService.GetList();
            ViewBag.ItemList = itemService.GetList();
            ViewBag.Id = id;

            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Update(GoodsIssueResource grRes)
        {
            try
            {
                giService.Update(grRes);
                return Ok();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.GetBaseException().Message);
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult Delete(Guid id)
        {
            giService.Delete(id);
            return Ok();
        }

        [Authorize]
        public IActionResult Print(Guid id)
        {
            var res = giService.Get(id);
            return View(res);
        }
    }
}

Inventory/Controllers/ItemController.cs
using Inventory.Models;
using Inventory.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Inventory.Controllers
{
    public class ItemController : Controller
    {
        private readonly ItemService itemService;

        public ItemController(ItemService itemService)
        {
            this.itemService = itemService;
        }

        [Authorize]
        public IActionResult Index(string keyword)
        {
            ViewBag.Keyword = keyword;

            var itemList = itemService.GetList(keyword);
            
            return View(itemList);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewBag.Action = "Create";
            return View("CreateUpdate");
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create(Item item)
        {
            try
            {
                itemService.Create(item);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Action = "Create";
                ViewBag.ErrorMessage = ex.Message;
                return View("CreateUpdate", item);
            }
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Update(Guid id)
        {
            ViewBag.Action = "Update";
            var item = itemService.Get(id);
            return View("CreateUpdate", item);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Update(Item item)
        {
            try
            {
                itemService.Update(item);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Action = "Update";
                ViewBag.ErrorMessage = ex.Message;
                return View("CreateUpdate", item);
            }
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(Guid id)
        {
            itemService.Delete(id);
            return Ok();
        }

        [Authorize]
        public IActionResult Get(Guid id)
        {
            var item = itemService.Get(id);
            return Ok(item);
        }
    }
}

Inventory/Controllers/UserController.cs
using Inventory.Models;
using Inventory.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Inventory.Controllers
{
    public class UserController : Controller
    {
        private readonly UserService userService;

        public UserController(UserService userService)
        {
            this.userService = userService;
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Index(string keyword)
        {
            ViewBag.Keyword = keyword;

            var userList = userService.GetList(keyword);
            
            return View(userList);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewBag.Action = "Create";
            return View("CreateUpdate");
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create(User user)
        {
            try
            {
                userService.Create(user);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Action = "Create";
                ViewBag.ErrorMessage = ex.Message;
                return View("CreateUpdate", user);
            }
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Update(Guid id)
        {
            ViewBag.Action = "Update";
            var user = userService.Get(id);
            return View("CreateUpdate", user);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Update(User user)
        {
            try
            {
                userService.Update(user);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Action = "Update";
                ViewBag.ErrorMessage = ex.Message;
                return View("CreateUpdate", user);
            }
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(Guid id)
        {
            userService.Delete(id);
            return Ok();
        }
    }
}

Inventory/Controllers/WarehouseController.cs
using Inventory.Models;
using Inventory.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Inventory.Controllers
{
    public class WarehouseController : Controller
    {
        private readonly WarehouseService warehouseService;

        public WarehouseController(WarehouseService warehouseService)
        {
            this.warehouseService = warehouseService;
        }

        [Authorize]
        public IActionResult Index(string keyword)
        {
            ViewBag.Keyword = keyword;

            var warehouseList = warehouseService.GetList(keyword);
            return View(warehouseList);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewBag.Action = "Create";
            return View("CreateUpdate");
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create(Warehouse warehouse)
        {
            try
            {
                warehouseService.Create(warehouse);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Action = "Create";
                ViewBag.ErrorMessage = ex.Message;
                return View("CreateUpdate", warehouse);
            }
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Update(Guid id)
        {
            ViewBag.Action = "Update";
            var warehouse = warehouseService.Get(id);
            return View("CreateUpdate", warehouse);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Update(Warehouse warehouse)
        {
            try
            {
                warehouseService.Update(warehouse);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Action = "Update";
                ViewBag.ErrorMessage = ex.Message;
                return View("CreateUpdate", warehouse);
            }
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(Guid id)
        {
            warehouseService.Delete(id);
            return Ok();
        }
    }
}

Inventory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-select/css/bootstrap-select.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inventory</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex flex-md-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Item</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Warehouse" asp-action="Index">Warehouse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GoodsReceipt" asp-action="Index">Goods Receipt</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GoodsIssue" asp-action="Index">Goods Issue</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StockReport" asp-action="Index">Stock Report</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Inventory
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-select/js/bootstrap-select.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Inventory/Views/Shared/_LayoutEmpty.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Inventory | Login</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>

    <div class="container">
        @RenderBody()
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>

Inventory/Views/Shared/_LayoutPrint.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/print.css" />
</head>
<body onload="window.print()">

    <div class="container">
        @RenderBody()
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>